import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import AppThemeProvider from "@/app/AppThemeProvider";
import Survey from "@/app/_suverys_assets/Survey";
import CssBaseline from '@mui/material/CssBaseline';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  ...props
}: Readonly<{
  children: React.ReactNode;
  props: object;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider {...props}>
          <CssBaseline />
          <Survey />
          <AppThemeProvider>
          {children}
          </AppThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
